### ISSUE TITLE
Kernel Not supported 

### ISSUE THREAD

**Issue by HugoMskn** [mayankmetha/Rucky#69] opened 2022-02-16 21:39 UTC
Hello,

After somes times I was able to unlock my P8 LITE 2017 PRA LX1's bootloader and installed lineageOS 17.1 with rooted thing

But Rucky is telling me that my kernel is not compatible

I've downloaded Rucky from the Nethunter Store

Should I install nethunter ?

OR is it any kernel that would be compatible and that I could flash ? or is there any tutorial to build my own kernel to enable HID attacks, or is there just a trick or something to install it ?

Cheers !

**Comment by mayankmetha** [comment] 2022-02-19 17:48
Duplicate of #8

**Closed by mayankmetha** 2022-02-19 17:48 UTC
Labels: duplicate, invalid, wontfix
