### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by AndraxBoy** [mayankmetha/Rucky#20] opened 2020-07-17 11:09 UTC
Hello can you add some more syntax:
MOUSE x:y — usb keyboard can click mouse with hid(NethunterStore), so can you add it here
WHILE like REPEAT but you can REPEAT 10 {
What you need to repeat
}
**Thx**

**Comment by mayankmetha** [comment] 2020-07-17 16:31
Duplicate of issue #11

**Closed** 2020-07-17 16:31 UTC
Labels: duplicate
